# Generated by Django 5.1.5 on 2025-02-03 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_title_menu_tittle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='tittle',
            new_name='title',
        ),
    ]
